# Use the official Python image as the base image
FROM python:3.10.4-slim
# Set the working directory inside the container
WORKDIR /app
# Copy the game code into the container
COPY game.py .
# Set the entry point command
CMD ["python", "game.py"]